### ISSUE TITLE
Include in a objective C private pod

### ISSUE THREAD

**Issue by fabiomassimo** [AnthonyMDev/CrashlyticsRecorder#2] opened 2016-06-16 08:45 UTC
I'm trying to use Crashlytics Recorder to log errors from my private pod. In my podspec I'm using following:

``` ruby
s.dependency 'CrashlyticsRecorder'
```

Unfortunately, from my objective C file in my private pod I'm not able to add the `Recorder` to access the method that I need.

How should I proceed?

**Comment by AnthonyMDev** [comment] 2016-06-16 17:42
Have you added `@import CrashlyticsRecorder` to your Objective-C file?

**Comment by fabiomassimo** [comment] 2016-06-16 21:20
Yes I tried but `CrashlyticsRecorder` is still not available ¯_(ツ)_/¯

**Comment by AnthonyMDev** [comment] 2016-06-17 00:26
I'm not sure why this is happening given the information you have provided. Can you provide a test project that I can recreate the issue in?

**Comment by AnthonyMDev** [comment] 2016-07-07 23:03
Since I can't reproduce this and have not received a response from you, I'm going to close this ticket. Please feel free to re-open if you can provide more information!

**Closed as completed** 2016-07-07 23:02 UTC
Labels: question
